# docker run -p 3306:3306 --name my_db
# -e MYSQL_ROOT_PASSWORD=gokstad -d mysql:8.0.33

FROM mysql:8.0.33

# -e MYSQL_ROOT_PASSWORD=gokstad
ENV MYSQL_ROOT_PASSWORD=gokstad

# IKKE NØDVENDIG Å HA MED, men best practice
EXPOSE 3306